steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "docker/Dockerfile",
          #"--cache-from", "gcr.io/$PROJECT_ID/blockscout:latest", --uncomment after latest tag is built
          "-t", "gcr.io/$PROJECT_ID/blockscout:$COMMIT_SHA",
          "-t", "gcr.io/$PROJECT_ID/blockscout:latest", "."]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "docker/Dockerfile",
          "--build-arg", "DISABLE_WRITE_API=true",
          "--build-arg", "DISABLE_INDEXER=true",
          "--build-arg", "DISABLE_WEBAPP=true",
          #"--cache-from", "gcr.io/$PROJECT_ID/blockscout:api-latest", -- uncomment after latest tag is built
          "-t", "gcr.io/$PROJECT_ID/blockscout:api-$COMMIT_SHA",
          "-t", "gcr.io/$PROJECT_ID/blockscout:api-latest", "."]
    waitFor: ["-"]
images:
  - "gcr.io/$PROJECT_ID/blockscout:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/blockscout:api-$COMMIT_SHA"
options:
    machineType: 'E2_HIGHCPU_32'
timeout: 7200s
