steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "docker/Dockerfile",
          "--build-arg", "ENABLE_SOURCIFY_INTEGRATION=true",
          "--build-arg", "SOURCIFY_SERVER_URL=https://sourcify.dev/server",
          "--build-arg", "SOURCIFY_REPO_URL=https://repo.sourcify.dev/contracts/full_match/",
          "-t", "gcr.io/$PROJECT_ID/blockscout:$COMMIT_SHA", "."]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "docker/Dockerfile",
          "--build-arg", "ENABLE_SOURCIFY_INTEGRATION=true",
          "--build-arg", "SOURCIFY_SERVER_URL=https://sourcify.dev/server",
          "--build-arg", "SOURCIFY_REPO_URL=https://repo.sourcify.dev/contracts/full_match/",
          "--build-arg", "DISABLE_WRITE_API=true",
          "--build-arg", "DISABLE_INDEXER=true",
          "--build-arg", "DISABLE_WEBAPP=true",
          "-t", "gcr.io/$PROJECT_ID/blockscout:api-$COMMIT_SHA", "."]
    waitFor: ["-"]
images:
  - "gcr.io/$PROJECT_ID/blockscout:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/blockscout:api-$COMMIT_SHA"

timeout: 3600s
