steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args: [
          #Kaniko build params
          "--cache", "true",
          "--destination", "gcr.io/$PROJECT_ID/blockscout:$COMMIT_SHA",

          #Docker build params
          "build", "-f", "docker/Dockerfile",
          "-t", "gcr.io/$PROJECT_ID/blockscout:$COMMIT_SHA",
          "-t", "gcr.io/$PROJECT_ID/blockscout:latest", "."]
    waitFor: ["-"]
  - name: "gcr.io/kaniko-project/executor:latest"
    args: [
          #Kaniko build params
          "--cache", "true",
          "--destination", "gcr.io/$PROJECT_ID/blockscout:api-$COMMIT_SHA",

          #Docker build params
          "build", "-f", "docker/Dockerfile",
          "--build-arg", "DISABLE_WRITE_API=true",
          "--build-arg", "DISABLE_INDEXER=true",
          "--build-arg", "DISABLE_WEBAPP=true",
          "-t", "gcr.io/$PROJECT_ID/blockscout:api-$COMMIT_SHA",
          "-t", "gcr.io/$PROJECT_ID/blockscout:api-latest", "."]
    waitFor: ["-"]
options:
    machineType: 'E2_HIGHCPU_32'
timeout: 1200s
