version: "3.9"
services:
  db:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"
volumes:
  pgdata:
